### ISSUE TITLE
新提交的编译问题

### ISSUE THREAD

**Issue by Andy5972** [GPBeta/nc.js#1]
buffer.cpp(926): error C2039: “IsIntValue”: 不是“CefV8Value”的成员
cef3\include\cef_v8.h(350) : 参见“CefV8Value”的声明

**Comment by GPBeta** [comment]
你是 debug 版本编译出现这个问题吧?

**Comment by Andy5972** [comment]
恩

**Comment by Andy5972** [comment]
这个 release 编译居然过了

**Comment by Andy5972** [comment]
去掉Value 后编译通过了 
v8_h 里 CefV8Value的定义 只是 IsInt IsUInt

**Comment by Andy5972** [comment]
我将buffer 中使用CefV8Value Is方法的Value去掉 debug编译测试 通过

**Comment by GPBeta** [comment]
新提交已经修复了这个问题.
对了, 你的 CEF 是哪个 branch 的?

On Thu, Jun 23, 2016 at 2:28 PM, shaojava notifications@github.com wrote:

> 我将buffer 中使用CefV8Value Is方法的Value去掉 debug编译测试 通过
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/GPBeta/nc.js/issues/1#issuecomment-227961422, or mute
> the thread
> https://github.com/notifications/unsubscribe/AMkRrmRLLUUKnWRGz9JKnPbd6h1-KHF3ks5qOiecgaJpZM4I8Zo_
> .

## 

Regards,
Joshua GPBeta

**Comment by Andy5972** [comment]
Branch 2454
